# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crawler.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'crawler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcrawler.proto\"M\n\x07\x43rawler\x12\x12\n\nuser_agent\x18\x01 \x01(\t\x12\x14\n\x0chttp_timeout\x18\x02 \x01(\x05\x12\x18\n\x10\x66ollow_redirects\x18\x03 \x01(\x08\"\xed\x01\n\x0e\x43rawlerService\x12\x1a\n\x08\x63rawlers\x18\x01 \x03(\x0b\x32\x08.Crawler\x12+\n\x06\x61\x64mins\x18\x02 \x03(\x0b\x32\x1b.CrawlerService.AdminsEntry\x12\x11\n\tlog_level\x18\x03 \x01(\x05\x1aN\n\x0b\x41\x64minsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0e\x32\x1f.CrawlerService.AdminPermission:\x02\x38\x01\"/\n\x0f\x41\x64minPermission\x12\x0e\n\nREAD_WRITE\x10\x00\x12\x0c\n\x08GOD_MODE\x10\x01\x42_\n\x1e\x63om.protoconf.examples.crawlerZ=github.com/protoconf/protoconf/examples/protoconf/src/crawlerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.protoconf.examples.crawlerZ=github.com/protoconf/protoconf/examples/protoconf/src/crawler'
  _globals['_CRAWLERSERVICE_ADMINSENTRY']._loaded_options = None
  _globals['_CRAWLERSERVICE_ADMINSENTRY']._serialized_options = b'8\001'
  _globals['_CRAWLER']._serialized_start=17
  _globals['_CRAWLER']._serialized_end=94
  _globals['_CRAWLERSERVICE']._serialized_start=97
  _globals['_CRAWLERSERVICE']._serialized_end=334
  _globals['_CRAWLERSERVICE_ADMINSENTRY']._serialized_start=207
  _globals['_CRAWLERSERVICE_ADMINSENTRY']._serialized_end=285
  _globals['_CRAWLERSERVICE_ADMINPERMISSION']._serialized_start=287
  _globals['_CRAWLERSERVICE_ADMINPERMISSION']._serialized_end=334
# @@protoc_insertion_point(module_scope)
