# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from agent.api.proto import protoconf_service_pb2 as agent_dot_api_dot_proto_dot_protoconf__service__pb2


class ProtoconfServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeForConfig = channel.unary_stream(
                '/v1.ProtoconfService/SubscribeForConfig',
                request_serializer=agent_dot_api_dot_proto_dot_protoconf__service__pb2.ConfigSubscriptionRequest.SerializeToString,
                response_deserializer=agent_dot_api_dot_proto_dot_protoconf__service__pb2.ConfigUpdate.FromString,
                )


class ProtoconfServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeForConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtoconfServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeForConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeForConfig,
                    request_deserializer=agent_dot_api_dot_proto_dot_protoconf__service__pb2.ConfigSubscriptionRequest.FromString,
                    response_serializer=agent_dot_api_dot_proto_dot_protoconf__service__pb2.ConfigUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.ProtoconfService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProtoconfService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeForConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/v1.ProtoconfService/SubscribeForConfig',
            agent_dot_api_dot_proto_dot_protoconf__service__pb2.ConfigSubscriptionRequest.SerializeToString,
            agent_dot_api_dot_proto_dot_protoconf__service__pb2.ConfigUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
