# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent/api/proto/protoconf_service.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'agent/api/proto/protoconf_service.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\"/\n\x19\x43onfigSubscriptionRequest\x12\x12\n\x04path\x18\x01 \x01(\tR\x04path\"P\n\x0c\x43onfigUpdate\x12*\n\x05value\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyR\x05value\x12\x14\n\x05\x65rror\x18\x02 \x01(\tR\x05\x65rror2[\n\x10ProtoconfService\x12G\n\x12SubscribeForConfig\x12\x1d.v1.ConfigSubscriptionRequest\x1a\x10.v1.ConfigUpdate0\x01\x42`\n\x1a\x63om.protoconf.agent.api.v1ZBgithub.com/protoconf/protoconf/agent/api/proto/v1;protoconfserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.api.proto.protoconf_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.protoconf.agent.api.v1ZBgithub.com/protoconf/protoconf/agent/api/proto/v1;protoconfservice'
  _globals['_CONFIGSUBSCRIPTIONREQUEST']._serialized_start=74
  _globals['_CONFIGSUBSCRIPTIONREQUEST']._serialized_end=121
  _globals['_CONFIGUPDATE']._serialized_start=123
  _globals['_CONFIGUPDATE']._serialized_end=203
  _globals['_PROTOCONFSERVICE']._serialized_start=205
  _globals['_PROTOCONFSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
